version: '3'
services:

  openldap-fd:
    image: fusiondirectory
    environment:
      - ADMIN_PASS=0JcUIZYGkiqqecya
      - CONFIG_PASS=0JcUIZYGkiqqecya
      - DOMAIN=equantum.fr
      - FD_ADMIN=admin
      - FD_PASS=aQm445WYn
      - INSTANCE=eQuantum
      - PLUGIN_POSIX=TRUE
      - PLUGIN_MIXEDGROUPS=TRUE
      - PLUGIN_NETGROUPS=TRUE
      
    ports:
      - 8000:80
      - 389:389
    volumes:
      - openldap-data:/var/lib/openldap/
      - openldap-config:/etc/openldap/slapd.d/
    networks:
      default:
    deploy:
      resources:
        limits:
          memory: 256M
      restart_policy:
        condition: on-failure
      mode: global


volumes:
    openldap-data:
    openldap-config: